### ISSUE TITLE
Delete obsolete releases

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder-ansible#4]
- Delete old release directories in `{{ app_root_path }}/releases`
- Keep current revision (the directory that is linked to `{{ app_path }}`)
- Keep N most recent releases (default N should be 0)
- This should be implemented as an Ansible role

**Comment by dreikanter** [comment]
Need to test this:

```yaml
- name: Find all directories in releases folder
  find:
    paths="{{ app_dir }}/{{ releases }}"
    file_type=directory
  register: dirs

- name: Only last three releases
  file:
    path="{{ item.path }}"
    state=absent
  with_items:
    - "{{ (dirs.files | sort(attribute='ctime'))[:-3] }}"
```

Or this:

```yaml
- find:
    paths: ".../releases/"
    file_type: directory
    recurse: no
  register: release_dirs

- block:
    - set_fact:
        old_dirs: "{{ (release_dirs.files|sort(attribute='mtime', reverse=True))[3:] }}"
    - file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_dirs }}"
  when: release_dirs.matched > 3
```
